<?php

namespace ContainerBxD38wB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nm_AfPUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nm.afPU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nm.afPU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookReadController::saveBookRead' => ['privates', '.service_locator.egipcEH.App\\Controller\\BookReadController::saveBookRead()', 'getBookReadControllersaveBookReadService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\BookReadController:saveBookRead' => ['privates', '.service_locator.egipcEH.App\\Controller\\BookReadController::saveBookRead()', 'getBookReadControllersaveBookReadService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\BookReadController::saveBookRead' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\BookReadController:saveBookRead' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
        ]);
    }
}
