<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVYPfTOn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVYPfTOn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVYPfTOn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVYPfTOn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVYPfTOn\App_KernelDevDebugContainer([
    'container.build_hash' => 'VYPfTOn',
    'container.build_id' => '82cc9f5a',
    'container.build_time' => 1736435260,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVYPfTOn');
