<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNwcGIE1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNwcGIE1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNwcGIE1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNwcGIE1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNwcGIE1\App_KernelDevDebugContainer([
    'container.build_hash' => 'NwcGIE1',
    'container.build_id' => 'dd533fa2',
    'container.build_time' => 1736467876,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNwcGIE1');
